### ISSUE TITLE
Project data not reloaded

### ISSUE THREAD

**Issue by jennyxu6** [sebischair/amelietor#16]
Once the user has opened project A from 'Projects' page, data about project A is loaded. If the user goes back to 'Projects' page and selects another project, data will not be reloaded. Description above the tabs is updated, but the data displayed in tabs is still from A.

Same problem with tab 'design decisions' when redirected from 'quality attributes' or 'architectural elements'.

**Comment by manoj5864** [comment]
@jennyxu6 I have fixed the second part "with tab 'design decisions' when redirected from 'quality attributes' or 'architectural elements'."

I was not able to reproduce the case with projects.
